config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pleureuses do
    resources :bookings, only: %i[create]
  end


  resources :bookings, exept: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pleureuse


  def to_s
    "#{pleureuse.name} from: #{start_date} to: #{end_date}"
  end

  def total_days
    (end_date - start_date).to_i
  end

  def total_price
    return (total_days + 1) * pleureuse.price
  end
end

app/models/pleureuse.rb
class Pleureuse < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_pseudo_and_city,
    against: [ :pseudo, :city],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  def self.perform_search(keyword)
    if keyword.present?
    then Pleureuse.search_by_pseudo_and_city(keyword)
    else Pleureuse.all
    end
  end

  belongs_to :user
  has_many_attached :pictures
  validates :pseudo, presence: true
  validates :city, presence: true
  validates :gender, presence: true
  validates :price, presence: true

  GENDER = ['Male', 'Female']
  DRAMA = ['Maitresse', 'Accusation', 'Se roule par terre']

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :pleureuse
  has_one_attached :photo
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
before_action :configure_permitted_parameters, if: :devise_controller?
include Pundit

# Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :birthday, :photo])

  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :phone_number, :birthday, :photo])
end

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^static_pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create


    @pleureuse = Pleureuse.find(params[:pleureuse_id])
    @booking = Booking.new
    @booking.start_date = params[:booking][:start_date].split('to') [0]
    if params[:booking][:start_date].split(' to ') [1].nil?
    @booking.end_date = params[:booking][:start_date].split('to') [0]
    else
    @booking.end_date = params[:booking][:start_date].split(' to ') [1]
    end

    @booking.user = current_user
    authorize @booking

    @booking.pleureuse = @pleureuse


    if @booking.save
      redirect_to booking_path(@booking), notice: 'Votre réservation à été confirmée avec succès'
    else
      render 'pleureuses/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @pleureuse = @booking.pleureuse
    authorize @pleureuse
  end

def index
  @bookings = policy_scope(Booking).all
  @mybookings = current_user.bookings
  @background = ["https://images.unsplash.com/photo-1505693626181-b858934dce6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1052&q=80(178 kB)
","https://images.unsplash.com/photo-1505693626181-b858934dce6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1052&q=80(178 kB)","https://images.unsplash.com/photo-1484619817839-dfc3452be01f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=667&q=80","https://images.unsplash.com/photo-1556978255-8699ebacb579?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1048&q=80(141 kB)","https://images.unsplash.com/photo-1574808146141-fbd663cfb174?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80","https://images.unsplash.com/photo-1564434887573-4a2a234d9200?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80","https://images.unsplash.com/photo-1564887343163-92bba7c4234b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80","https://images.unsplash.com/photo-1528535619428-a995242b9096?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80","https://images.unsplash.com/photo-1549816044-47649bae10f6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1534&q=80","https://images.unsplash.com/photo-1506280225777-ced660ce8f16?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjExMDk0fQ&auto=format&fit=crop&w=1050&q=80"]


end

def edit
  @booking = Booking.find(params[:id])
  authorize @booking
end

def update
  @booking = Booking.find(params[:id])
  authorize @booking
  if @booking.update(booking_params)
  redirect_to booking_path(@booking), notice: 'Votre réservation à été confirmée avec succès'
  else
    render 'edit'
  end
end

def destroy
  @booking = Booking.find(params[:id])

  @booking.destroy
  authorize @booking
  redirect_to bookings_path
end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pleureuses_controller.rb
class PleureusesController < ApplicationController
skip_before_action :authenticate_user!, only: %i[index show]

  def index
     @pleureuse = policy_scope(Pleureuse).all
    if params[:search].present? || params[:drama_option].present?
      @pleureuses = Pleureuse.perform_search("#{params[:search]} #{params[:drama_option]}")
    else
      @pleureuses = Pleureuse.all
    end

    @photos = ["https://images.unsplash.com/photo-1573516515928-92444ec46ce2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1555&q=80","https://images.unsplash.com/photo-1566677379359-5ef1321fcb7e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80","https://images.unsplash.com/photo-1551823934-61391394a6ca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1993&q=80","https://images.unsplash.com/photo-1545792583-533185490f52?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=958&q=80","https://images.unsplash.com/photo-1567659893051-0b046978d0f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80", "https://images.unsplash.com/photo-1533392151650-269f96231f65?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80","https://images.unsplash.com/photo-1546189827-c4cd7d1cc07d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80","https://images.unsplash.com/photo-1551823934-3d82b4d2fd1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=2010&q=80"]
  end

  def show

    @pleureuse = Pleureuse.find(params[:id])
    authorize @pleureuse
  end

  def edit
    @pleureuse = Pleureuse.find(params[:id])
    authorize @pleureuse
  end

  def update
    @pleureuse = Pleureuse.find(params[:id])
    authorize @pleureuse
    @pleureuse.update(pleureuse_params)
      if @pleureuse.save
    redirect_to pleureuse_path(@pleureuse)
    else
    render "edit"
    end
  end

  def new

    @pleureuse = Pleureuse.new
    authorize @pleureuse
  end

  def create
    @pleureuse = Pleureuse.new(pleureuse_params)
    @pleureuse.user = current_user
    authorize @pleureuse
    if @pleureuse.save
    redirect_to pleureuse_path(@pleureuse)
    else
    render "new"
    end
  end


  def destroy
    @pleureuse = Pleureuse.find(params[:id])
    @pleureuse.destroy
    authorize @pleureuse
  end

  private

  def pleureuse_params
    params.require(:pleureuse).permit(:pseudo, :gender, :city, :price, :description, :drama_option, :language, :address, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
          <h2>Modifier</h2>
          <%= simple_form_for(@booking) do |f| %>
          <%= f.input :start_date, as: :hidden, input_html: {class: "datepicker", id:"range_start"} %>
          <%= f.input :end_date,as: :hidden, input_html: {class: "datepicker", id:"range_end"} %>
          <%= f.button :submit, "Modifier", class: "btn-flat"%>
          <%end%>

app/views/bookings/index.html.erb
<div class="container pt-3">
  <div class="d-flex justify-content-center">
    <h2>Mes réservations</h2>
  </div>
  <div class="d-flex flex-wrap">
      <div class="cards">
    <% @mybookings.each do |booking| %>
        <div class="card-trip">
            <img src= <%= @background.sample %>/>
          <div class="card-trip-infos ">

            <%= cl_image_tag booking.pleureuse.user.photo.key, alt: "alttext", class: "card-trip-user avatar-bordered" %>

            <div class="d-flex justify-content-between p-3" style="width: 100%" >

              <div>
                <h2>
                  <%=booking.pleureuse.pseudo%>
                </h2>
                <div>
                  Du : <%=booking.start_date.strftime('%d-%m-%Y')%>
                </div>
                <div>
                  Au : <%=booking.end_date.strftime('%d-%m-%Y')%>
                </div>
              </div>

              <div>
                <h1>
                  <%= booking.pleureuse.price %>€
                </h1>
              </div>

            </div>

          </div>
          <div class="d-flex align-items-center justify-content-end">
          <div class="p-3">
          <%= link_to "Modifier", edit_booking_path(booking), class: "btn-flat" %>
          </div>
          <div class="p-3">

            <button id="sweet-alert-demo" class="btn btn-danger">Supprimer</button>
            <%= link_to "", booking_path(booking), method: :delete, id: "delete-link", class: "hidden" %>

          </div>
          </div>
        </div>
      <%end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <br>
  <div class="row justify-content-center">
    <div class ="col-lg-8 col-sm-6 border bg-white shadow-sm p-3 mb-5 bg-white rounded">
      <h1 class= "row justify-content-center display-4">Merci pour votre reservation</h1>
      <h2 class= "row lead justify-content-center"> <strong>Votre pleureuse est : <%= @pleureuse.pseudo %></strong></h2>
      <hr class="my-4">
      <p class= "row justify-content-center"><strong>Début de réservation : </strong> <%=  @booking.start_date.strftime('%d-%m-%Y') %></p>
      <p class= "row justify-content-center"> <strong>Fin de réservation :  </strong> <%=  @booking.end_date.strftime('%d-%m-%Y') %></p>
      <h2 class="row my-4 justify-content-center">Prix total <%= @booking.total_price %> €</h2>
      <a class="row btn-flat btn-flat-3 justify-content-center" href="#" role="button">Payer</a>
      <br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pleureuses en or</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!--<p class="notice"><%= notice %></p> -->
    <!--<p class="alert"><%= alert %></p> -->
    <div class="content-wrapper">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1522752622479-65eefd320386?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2560&q=80);">
  <div class="container">
    <h1>Ayez l'enterrement que vous voulez, pas celui que vous meritez!</h1>
    <p>Bookez votre pleureuse maintenant</p>
    <% if !current_user %>
      <%= link_to "Se connecter", new_user_session_path, class: "btn btn-ghost2"%>
    <% else %>
      <%= link_to "Decouvrez les pleureuses", pleureuses_path, class: "btn btn-ghost2"%>
    <% end %>
  </div>
</div>

  <div class="container">
    <div class="d-flex justify-content-between" >

      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="box">
        <%= image_tag "funeral.svg", height: 100 %>
        <h3 class="text-center"> Simulez votre enterrement</h3>
        <p class="text-center"> Assistez à votre enterrement simulé pour mieux ajuster votre attestament </p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="box">
        <%= image_tag "rocket.svg", height: 100 %>
        <h3 class="text-center">Boostez votre popularité </h3>
        <p class="text-center"> Soyez toujours active depuis l’au delà</p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="box">
        <%= image_tag "award.svg", height: 100 %>
        <h3 class="text-center">Meilleur service "après mort"</h3>
        <p class="text-center">Aucun de nos clients est revenu de la mort pour se plaindre</p>
        </div>
      </div>
    </div>
<!--       <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
   @ 2020 Pleureuse. All rights Reserved</i>
</div> -->
  </div>

app/views/pleureuses/edit.html.erb
<div class="container p-4">
  <div class="row justify-content-center">
    <div class ="col-sm-6 col-sm-offset-6">
      <div class="Box">
        <div class="shadow-sm p-3 mb-5 bg-white rounded">

      <h2 class="row justify-content-center">Modifiez votre profil de pleureuse</h2>

      <%= simple_form_for @pleureuse do |f| %>
        <div class="form-inputs">
          <%= f.input :pseudo%>
          <%= f.input :gender, collection: Pleureuse::GENDER, as: :radio_buttons %>
          <%= f.input :drama_option, collection: Pleureuse::DRAMA, as: :radio_buttons %>
          <%= f.input :price%>
          <%= f.input :city%>
          <%= f.input :description%>
          <%= f.input :language%>
          <%= f.input :address%>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Edit pleureuse", class: "btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pleureuses/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1517545084371-4a575dde2a02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80');">
  <div class="container">
    <h1>Trouvez la bonne pleureuse pour vos funérailles</h1>
    <p>La meilleure pleureuse pour toutes sortes d'enterrements ou d'événements.</p>

  <form class="form-inline">
    <div class="row">
      <div class="form-group col-xs-3">
        <%= form_tag pleureuses_path, method: :get do %> <%= text_field_tag :search,
            params[:search],
            class: "form-control",
            placeholder: "Où est votre enterrement?"
          %>
      <div class="form-group col-xs-3">
          <%= text_field_tag :drama_option,
            params[:drama_option],
            class: "form-control",
            placeholder: "Type de drame"
          %>
      </div>
          <%= submit_tag "Search", class: "btn btn-outline-light" %>
        <% end %>
      </div>

    </div>
  </form>
  </div>
</div>
<br>
<div class="container">
  <br>
  <div class="cards">
    <%@pleureuses.each do |pleureuse| %>
    <%= link_to pleureuse_path(pleureuse) do  %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= pleureuse.picture %>">
          <center>
          <%= pleureuse.pseudo %>
            <br>
            <font size="3"><%= pleureuse.city %></font>
          </center>
        </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/pleureuses/new.html.erb
<div class="container p-4">
  <div class="row justify-content-center">
    <div class ="col-sm-6 col-sm-offset-6" >
      <div class="Box">
        <div class="shadow-sm p-3 mb-5 bg-white rounded">

      <h2 class="row justify-content-center">Devenez une pleureuse hors paire</h2>

      <%= simple_form_for @pleureuse do |f| %>
        <div class="form-inputs p-3">
          <%= f.input :pseudo%>
          <%= f.input :gender, collection: Pleureuse::GENDER, as: :radio_buttons %>
          <%= f.input :drama_option, collection: Pleureuse::DRAMA, as: :radio_buttons %>
          <%= f.input :price%>
          <%= f.input :city%>
          <%= f.input :language%>
          <%= f.input :address%>
          <br>
          <%= f.input :description%>

        </div>

          <%#= simple_fields_for :drama do |x| %>
            <%# Pleureuse::DRAMA.each do |option| %>
              <%#= x.input option.to_sym, as: :boolean %>
            <%# end %>
          <%# end %>

        <div class="form-actions">
          <%= f.button :submit, "Add pleureuse", class: "btn-flat"%>
        </div>
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_card.html.erb
<% @pleureuses.each do || %>
<div class="col-xs-12 col-sm-4">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= pleureuse.photo.file.nil? ? "https://images.unsplash.com/photo-1517545084371-4a575dde2a02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" : cloudinary_url(space.photo) %>);">
    <div class="card-description">
      <h2><%= pleureuse.pseudo  %></h2>
      <p><%= pleureuse.city %>, <%= pleureuse.gender %>, <%= pleureuse.price %></p>
    </div>
    <img class="card-user" src=<%= User.find(pleureuse.user_id).photo.file.nil? ? "https://via.placeholder.com/150" : cloudinary_url(User.find(pleureuse.user_id).photo) %>>
    <%= link_to "", pleureuse_path(pleureuse), { class: "card-link" } %>
  </div>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="flash alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- Site footer -->
  <br>
  <footer class="site-footer">
      <div class="container w-100">
        <div class="row w-100">
          <div class="col-sm-12 col-md-6">
            <h6>A propos</h6>
            <p class="text-justify">Pleureuses : <i>devenez populaire après votre mort </i> est une initiative pour vous permettre de ne pas être enterré seul.</p>
            <p>Nous sommes là quand vous ne l'êtes plus</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">Pleureuses</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">Devenir Pleureuse</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">La concurrance</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>En savoir plus</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">A propos</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribuer</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
         <a href="https://www.youtube.com/watch?v=eY9IGY8-NvE&list=PLE7E863E34331F743">Pleureuses</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="https://www.facebook.com/events/462322884657009/"><i class="fab fa-facebook-f "></i></a></li>
              <li><a class="twitter" href="https://twitter.com/meganamram?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="https://www.reddit.com/r/counting/"><i class="fab fa-reddit"></i></a></li>
              <li><a class="linkedin" href="https://www.linkedin.com/in/barackobama"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="d-flex align-items-center" >
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "christian-grave.png" %>
    <% end %>
    <h3>Pleureuses en or</h3>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "✞ Devenir Pleureuse ✞", new_pleureuse_path, class: "btn-flat"%>
        </li>

        <li class="nav-item">
          <%= link_to "Liste de pleureuses", pleureuses_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag "#{current_user.photo.key}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", edit_user_registration_path(current_user) , class: "dropdown-item" %>
              <%= link_to "Devenir pleureuse", new_pleureuse_path, class: "dropdown-item"  %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item"  %>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          <% else %>
            <%= image_tag ("https://pbs.twimg.com/profile_images/564429257850761216/jZ51D5Zr.jpeg"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", edit_user_registration_path(current_user) , class: "dropdown-item" %>
              <%= link_to "Devenir pleureuse", new_pleureuse_path, class: "dropdown-item"  %>
              <%= link_to "Mes réservations", bookings_path, class: "dropdown-item"  %>
              <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>